config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :alunos
  resources :classes
  resources :ferramentas
  
  get 'dashboard/index'  
  root to: 'dashboard#index'


end

app/models/aluno.rb
class Aluno < ApplicationRecord
    has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :foto , content_type: /\Aimage\/.*\z/ #validação para fazer upload somente de fotos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classe.rb
class Classe < ApplicationRecord
    has_many :alunos
end

app/models/sexo.rb
class Sexo < ApplicationRecord
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
    before_action :set_aluno, only: [:show, :edit, :update, :destroy]
    before_action :set_classes_options, only: [:new, :create ,:edit ,:update]
    #metodos internos
   

    def calc_media(b1,b2)
        media = (b1+b2)/2
        return media
    end

    def atualiza_status(media)
        if media >= 7
            status = true
            return status
        else
            status = false
            return status
        end
    end    

    #Fim metodos internos

    
    def index
        @alunos = Aluno.all
    end

    def show
    end

    def new
        @aluno = Aluno.new
    end

    def edit
    end
    
    def update
        respond_to do |format|
            if @aluno.update (aluno_params)
                media = calc_media(@aluno.b1,@aluno.b2)
                status = atualiza_status(media)
                @aluno.update_attribute(:media, media)
                @aluno.update_attribute(:status, status)

                format.html {redirect_to @aluno, notice: 'Aluno atualizado com sucesso!'}
                format.json {render :show,status: :ok, location: @aluno}
            else
                format.html {render :edit}
                format.json {render json: @aluno.erros, status: :unprocessable_entity}
            end
        end
    end

    def destroy
        @aluno.destroy
        respond_to do |format|
            format.html {redirect_to alunos_path,notice: 'Aluno excluido com sucesso!'}
            format.json {head :no_content}
        end
    end


    def create
        @aluno = Aluno.new(aluno_params)
        media = calc_media(@aluno.b1,@aluno.b2)
        status = atualiza_status(media)

        @aluno.media = media
        @aluno.status = status
        
        respond_to do |format|
        
        if @aluno.save
            format.html{redirect_to @aluno,notice: 'Aluno cadastrado com sucesso!'}
            format.json{render :show, status: :created, location: @aluno }    
        else
            format.html{render :new}
            format.json{render json: @aluno.errors, status: :unprocessable_entity}
        end
    end
end

    
    private 
    def set_aluno
        @aluno = Aluno.find(params[:id])
    end

    def aluno_params
        params.require(:aluno).permit(:nome,:classe_id,:sexo,:endereco,:data_nasc,:b1,:b2,:foto,:telefone)
    end

    def set_classes_options
        @classes_options = Classe.all.pluck(:nome,:id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale
    def set_locale
        if params[:locale]
            cookies[:locale]=params[:locale]
        end
        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
    end
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
    before_action :set_classe, only: [:show, :edit, :update, :destroy]
    
    def index
        @classes = Classe.all
    end

    def new
        @classe = Classe.new
    end

    def create
        @classe = Classe.new(classe_params)
        respond_to do |format|
        if @classe.save
            format.html{redirect_to @classe,notice: 'Classe cadastrado com sucesso!'}
            format.json{render :show, status: :created, location: @classe }
        else
            format.html{render :new}
            format.json{render json: @classe.errors, status: :unprocessable_entity}
        end
    end
end

    def show
    
    end
    def edit
    
    end
    def update
        respond_to do |format|
            if @classe.update (classe_params)
                format.html {redirect_to @classe, notice: 'Classe atualizada com sucesso!'}
                format.json {render :show,status: :ok, location: @classe}
            else
                format.html {render :edit}
                format.json {render json: @classe.erros, status: :unprocessable_entity}
            end
        end
    end

    def destroy
        @classe.destroy
        respond_to do |format|
        format.html {redirect_to classes_path,notice: 'Classe excluida com sucesso!'}
        format.json {head :no_content}
        end
    end



    private 
    def set_classe
        @classe = Classe.find(params[:id])
    end

    def classe_params
        params.require(:classe).permit(:nome)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/ferramentas_controller.rb
class FerramentasController < ApplicationController




    def calculadora (operacao)
        Case operacao
        when '+'
            return sum(num1,num2)
        
        
    end








end

app/helpers/alunos_helper.rb
module AlunosHelper
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_data (data)
        data.strftime("%d/%m/%Y")
    end
    
    def classe_identifica(id)
        classes = Classe.all 
        classes.each do |classe|
            if classe.id == id
               return classe.nome
            else
                "Classe Não Cadastrada"
            end
          end
    end

    def aprovacao(status)
        if status == true
            return :accredited
        else
            return :disapproved
        end
    end

    def format_telefone(telefone)
        tel = ''
        telefone = telefone.to_s
        tel << '('+ telefone[0..1]
        tel << ')'+ telefone[2..6]
        tel << '-'+ telefone[7..10]
        return tel
    end

end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/ferramentas_helper.rb
module FerramentasHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno,local: true,  html: { multipart: true }) do |form|%>
<div class="container">
  <div class="notification">
    <div class="columns is-desktop">
      <div class="column">
        <div class="box">
          <strong>Dados Pessoais:</strong>
          <br>
          <br>
          <%#= form_with(model: aluno,local: true,  html: { multipart: true }) do |form|%>
          <p>
            <%= form.label :foto %>
            <%= form.file_field :foto %>
          </p>
          <br>
          <p>
            <div class="field">
              <%= form.label :nome%>
              <%= form.text_field :nome%>
            </div>
          </p>
          <p>
            <div class="field">
              <%=form.label :data_nasc%>
              <%=form.date_select :data_nasc, start_year: 1970%>
            </div>
          </p>
          <p>
            <div class="field">
              <%= form.label :sexo%>
              <%=select(:aluno, :sexo ,([['Masculino','M'],['Feminino','F']]))%>
            </div>
          </p>
          <p>
            <div class="field">
              <%= form.label :telefone%>
              <%= form.text_field :telefone%>
              <small><i>*Digite apenas números ex: 12912341234</i></small>
            </div>
          </p>
          <p>
            <div class="field">
              <%= form.label :endereco%>
              <%= form.text_field :endereco%>
            </div>
          </p>
        </div>
      </div>
      
      <div class="column">
        <div class="box">
          <strong>Dados Escolares:</strong>
          <br>
          <br>
          <p>
            <div class="field">
              <%= form.label :classe%>
              <%= form.select('classe_id',@classes_options ,{include_blank: "Selecione..."})%>
              <%#Funcionam também, mas o mais correto é a linha de cima.%>
              <%#= form.collection_select :classe_id, Classe.all, :id, :nome %>
            </div>
          </p>
          <p>
            <div class="field">
              <%=form.label :b1%>
              <%=form.text_field :b1%>
            </div>
          </p>
          <p>
            <div class="field">
              <%=form.label :b2%>
              <%=form.text_field :b2%>
            </div>
          </p>
        </div>  
      </div>
    </div>
    <div class="actions">
      <input class="button" type="submit" name="commit" value="Salvar">
      <%#<input class="button" type="submit" name="commit" value="Salvar" data-disable-with="Create Aluno"/>%>
    </div>
  </div>
</div>
<%end%>
<br>

app/views/alunos/edit.html.erb
<div class="hero">
	<div class="container is-widescreen">
		<h1 class="title">
			Editar Aluno:
		</h1> 
	</div>
</div>

<%= render 'form', aluno: @aluno %>

<div class="container">
	<div class="notification">

		<button class="button is-outlined"><%= link_to 'Mostrar', @aluno %></button>
		<button class="button is-outlined"><%= link_to 'Voltar',  alunos_path%></button>
	</div>
</div>

app/views/alunos/editando_form.html.erb
    <div class="box">
      <strong>Dados Pessoais:</strong>
      <br>
      <br>
      <%= form_with(model: aluno,local: true,  html: { multipart: true }) do |form|%>
      <p>
        <%= form.label :foto %>
        <%= form.file_field :foto %>
      </p>
      <br>
      <p>
        <div class="field">
          <%= form.label :nome%>
          <%= form.text_field :nome%>
        </div>
      </p>
      <p>
        <div class="field">
          <%=form.label :data_nasc%>
          <%=form.date_select :data_nasc, start_year: 1970%>
        </div>
      </p>
      <p>
        <div class="field">
          <%= form.label :sexo%>
          <%=select(:aluno, :sexo ,([['Masculino','M'],['Feminino','F']]))%>
        </div>
      </p>
      <p>
        <div class="field">
          <%= form.label :telefone%>
          <%= form.text_field :telefone%>
          <small><i>*Digite apenas números ex: 12912341234</i></small>
        </div>
      </p>
      <p>
        <div class="field">
          <%= form.label :endereco%>
          <%= form.text_field :endereco%>
        </div>
      </p>
    </div>
  </div>

    <div class="box">
      <strong>Dados Escolares:</strong>
      <br>
      <br>
      <p>
        <div class="field">
          <%= form.label :classe%>
          <%= form.select('classe_id',@classes_options ,{include_blank: "Selecione..."})%>
          <%#Funcionam também, mas o mais correto é a linha de cima.%>
          <%#= form.collection_select :classe_id, Classe.all, :id, :nome %>
        </div>
      </p>
      <p>
        <div class="field">
          <%=form.label :b1%>
          <%=form.text_field :b1%>
        </div>
      </p>
      <p>
        <div class="field">
          <%=form.label :b2%>
          <%=form.text_field :b2%>
        </div>
      </p>
      <p>
        <div class="actions">
          <%= form.submit %>
          <%#<input class="button" type="submit" name="commit" value="Salvar" data-disable-with="Create Aluno"/>%>
        </div>
        <%end%>
        </p>
      </div>  
  </div>
</div>

<br>

app/views/alunos/index.html.erb
<div>
  <div class="hero-body">
    <h1 class = title><%=t(:student)%>
    </h1>
  </div>
  <div class="container">
    <div class="notification">
      <button class="button is-outlined"><%= link_to t(:new), new_aluno_path %></button>
    </div>
  </div>
  <div class ="hero-body">
    <div class="container has-text-centered">
      <table class= "table is-striped is-fullwidth">
        <thead>
          <tr>
            <th>id</th>
            <th><%=t(:name)%></th>
            <th><%=t(:class)%></th>
            <th><%=t(:birthday)%></th>
            <th><%=t(:status)%></th>
          </tr>
        </thead>
        <tbody>
          <% @alunos.each do |aluno|%>
            <tr>
              <td><%= aluno.id%></td>
              <td><%= aluno.nome%></td>
              <td><%= classe_identifica(aluno.classe_id)%></td>
              <td><%= format_data(aluno.data_nasc)%></td>
              <% if aluno.status == true%>
                <td><font color="green"><b><%=t(aprovacao(aluno.status))%></b></font></td>
              <%else%>
                <td><font color="red"><b><%=t(aprovacao(aluno.status))%></b></font></td>
              <%end%>
              <td><button class="button is-outlined"><%= link_to t(:show), aluno %></button></td>
              <td><button class="button is-outlined"><%= link_to t(:edit), edit_aluno_path(aluno)%></button></td>
              <td><button class="button is-outlined"><%= link_to t(:delete), aluno,method: :delete, data: {confirm: 'Tem certeza que deseja excluir?'}%></button></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
  <br>
  <hr>
  <body>
    <section class="section">
      <div class="container">
        <h1 class="title">Section</h1>
        <h2 class="subtitle">
          A simple container to divide your page into <strong>sections</strong>, like the one you're currently reading
        </h2>
      </div>
    </section>
  </body>
  <hr>
  <%#= link_to 'Home', dashboard_index_path %>

app/views/alunos/new.html.erb
<div class="hero">
	<div class="notification">
		<h1 class="title">
			Novo Aluno:
		</h1> 
	</div>
</div>

<%= render 'form', aluno: @aluno %>


<div class="container">
	<div class="notification">
		<button class="button is-outlined"><%= link_to 'Voltar', alunos_path %></button>
	</div>
</div>

app/views/alunos/show.html.erb
     <% if notice%>
     <div class="notification is-warning is-light">
      <p id="notice"><%=notice%></p>
    </div>
    <%end%>
    <div class="container">
      <div class="notification">
    <div class="hero">
      <div class="container is-widescreen">
        <h1 class="title"><%=t(:student_data)%>:</h1> 
      </div>
    </div>

    <div class="columns is-desktop">
      <div class="column">
        <div class="box">
          <strong>Dados Pessoais:</strong>
          <br>
          <article class="media">
            <div class="media-left">
              <figure class="image is-64x64">
                <img class="is-rounded" src= <%= @aluno.foto.url(:medium) %> />
              </figure>
            </div>
            <div class="media-content">
              <p>
                <strong>Id:</strong>
                <%= @aluno.id %>
              </p>

              <p>
                <strong><%=t(:name)%>:</strong>
                <%=@aluno.nome%>
              </p>

              <p>
                <strong><%=t(:birthday)%>:</strong>
                <%=format_data(@aluno.data_nasc)%>
              </p>

              <p>
                <strong>Sexo:</strong>
                <%=@aluno.sexo%>
              </p>

              <p>
                <strong>Telefone:</strong>
                <%if @aluno.telefone != nil%>
                <%=format_telefone(@aluno.telefone.to_s)%>
                <%else%>
                <i>Telefone não cadastrado </i>
                <%end%>
              </p>

              <p>
                <strong>Endereço:</strong>
                <%=@aluno.endereco%>
              </p>
            </div>
          </article>
        </div>
      </div>

      <div class="column">
        <div class="box">
          <strong>Dados Escolares:</strong>
          <p>
            <strong>Classe:</strong>
            <%=classe_identifica(@aluno.classe_id)%>
          </p>
          <h1>alo mundo</h1>
          <p>
            <strong>B1:</strong>
            <%=@aluno.b1%>
          </p>

          <p>
            <strong>B2:</strong>
            <%=@aluno.b2%>
          </p>

          <p>
            <strong>Media:</strong>
            <%=@aluno.media%>
          </p>

          <p>
            <strong>Status:</strong>
            <%=aprovacao(@aluno.status)%>
          </p>
        </div>
      </div>
    </div>
</div>
</div>
    <div class="container">
      <div class="notification">
        <button class="button is-outlined"><%= link_to 'Voltar', alunos_path %></button>
        <button class="button is-outlined"><%= link_to 'Editar', edit_aluno_path(@aluno)%></button>
      </div>
    </div>

app/views/classes/_form.html.erb
  <div class="hero-body">
  <div class = "notification">
    <%= form_with(model: classe,local: true) do |form|%>
    <p>
         <div class="field">
            <%= form.label :nome%>
            <%= form.text_field :nome%>   
        </div>
    </p>   
    <p>  
        <div class="actions">
            <div class="actions">
           <input class="button" type="submit" name="commit" value="Salvar" data-disable-with="Create Classe" /></button>
         </div>
        </div>
        </p>
    <%end%>
    </div>
</div>
</div>

app/views/classes/edit.html.erb
<div class="hero">
    <div class="notification">
      <h1 class="title">
        Editar Classe:
      </h1> 
    </div>
  </div>

<%= render 'form', classe: @classe %>

<button class="button is-outlined"><%= link_to 'Mostrar', @classe %></button>
<button class="button is-outlined"><%= link_to 'Voltar',  class_path%></button>

app/views/classes/index.html.erb
<div>
<% if notice%>
<div class="hero">
    <div class="notification">
      <p id="notice"><%=notice%></p>
    </div>
  </div>
<%end%>

    <div class="hero-body">
    <h1 class = title> <%=t(:class)%>
    </h1>
</div>

    <button class="button is-outlined"><%= link_to t(:new), new_class_path %></button>

<div class ="hero-body">
    <div class="container has-text-centered">
    <table class= "table is-striped is-fullwidth">
    <thead>
    <tr>
        <th>id</th>
        <th><%=t(:class)%></th>
    </tr>
    </thead>
            <tbody>
            <% @classes.each do |classe|%>
            <tr>
            <td><%= classe.id%></td>
            <td><%= classe.nome%></td>
            <td><button class="button is-outlined"><%= link_to t(:show), classe %></button></td>
            <td><button class="button is-outlined"><%= link_to t(:edit), edit_class_path(classe)%></button></td>
            <td><button class="button is-outlined"><%= link_to t(:delete), classe,method: :delete, data: {confirm: 'Tem certeza que deseja excluir?'}%></button></td>
            </tr>
            <%end%>
        </tbody>
        </table>
</div>
</div>

<br>
<%#= link_to 'Home', dashboard_index_path %>

app/views/classes/new.html.erb
<div class="hero">
    <div class="notification">
      <h1 class="title">
        Nova Classe:
      </h1> 
    </div>
  </div>
<%= render 'form', classe: @classe %>

<button class="button is-outlined"><%= link_to 'Voltar', classes_path %></button>

app/views/classes/show.html.erb
<div class="hero">
    <div class="notification">
      <h1 class="title">
        Classe:
      </h1> 
    </div>
  </div>

    <% if notice%>
        <div class="hero">
            <div class="notification">
            <p id="notice"><%=notice%></p>
            </div>
        </div>
    <%end%>
  <div class="hero-body is-bold">
  <div class = "notification">
    <p>
    <strong>Id:</strong>
    <%= @classe.id %>
    </p>

    <p>
    <strong>Nome:</strong>
        <%=@classe.nome%>
    </p>

    </div>
</div>
<button class="button is-outlined"><%= link_to 'Voltar', classes_path %></button>
<button class="button is-outlined"><%= link_to 'Editar', edit_class_path(@classe)%></button>

app/views/dashboard/index.html.erb
<div>
    <section class= "hero is-light is-medium is-bold">
        <div class = "hero-body">
            <div class = "container has-text-centered">
                <%#= image_tag "https://i.pinimg.com/originals/5f/fb/de/5ffbdeceb84323decd76084b2efca958.png", size:"150x150"%>
                <%= image_tag "https://www.acessogeo.com.br/images/logogeo.jpg", size:"400x400"%>
        </div>
    </div>
   </section>
</div>

app/views/ferramentas/index.html.erb
<h1><%=t(:tools)%></h1>

app/views/layouts/_footer.html.erb
<p><small><center> Cats_Code LTDA - Todos os direitos reservados</center></small> </p>